name: Build, Test ad Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Instal Dependencies
      run: npm i
    - name: Instal Playwright browser
      run: npx playwright install
    
    - name: Change the backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start the Backedn
      run: npm run start-be &
    - name: Start the FrontEnd
      run: npm run start-fe &
    - name: Execute UI Tests
      run: npm run test


  deploy-be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_BE_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true

  deploy-fe:
    runs-on: ubuntu-latest
    needs: deploy-be
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_FE_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true